{
 "title": "Glitchtip Project Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "org_slug", "label": "Organization", "query": { "query": "glitchtip_projects" } },
   {
    "name": "project_slug",
    "label": "Project",
    "query": {
     "query": "glitchtip_events_created{organization=\"$org_slug\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Events/Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(glitchtip_events_total{organization=\"$org_slug\", project=\"$project_slug\"}[$__interval]) * 60)",
     "legendFormat": "Events/Minute"
    }
   ]
  },
  {
   "title": "Number of Issues/Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(glitchtip_issues_total{organization=\"$org_slug\", project=\"$project_slug\"}[$__interval]) * 60)",
     "legendFormat": "Events/Minute"
    }
   ]
  },
  {
   "title": "Top 10 Issues",
   "type": "bargauge",
   "description": "Number of events per issue in the selected time range",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Events" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, increase(glitchtip_events_total{organization=\"$org_slug\", project=\"$project_slug\"}[$__range]) > 0)",
     "legendFormat": "{{issue}}"
    }
   ]
  },
  { "title": "General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Number of Projects in Organization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(glitchtip_projects{organization=\"$org_slug\"})",
     "legendFormat": "Number of Projects"
    }
   ]
  },
  {
   "title": "Number of Events in Project",
   "type": "stat",
   "description": "Number of new events in the selected project in the selected time range",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glitchtip_events_total{organization=\"$org_slug\", project=\"$project_slug\"}[$__range]))",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Number of new Issues in Project",
   "type": "stat",
   "description": "Number of new issues in the selected project in the selected time range",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glitchtip_issues_total{organization=\"$org_slug\", project=\"$project_slug\"}[$__range]))",
     "legendFormat": "Events"
    }
   ]
  }
 ]
}