{
 "title": "Glitchtip-Django",
 "description": "Django metrics dashboard using django-prometheus metrics exporter",
 "tags": [
  "glitchtip",
  "django"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Glitchtip Instance", "query": "glitchtip" },
   {
    "name": "env",
    "query": "prod : app-sre-prod-04-prometheus, stage : app-sre-stage-01-prometheus"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(django_http_requests_total_by_method_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_view_transport_method_total{namespace=\"$namespace\", view=~\".*event_envelope.*|api:event_store.*\"}[$__interval]) * 60)",
     "legendFormat": "Events/Minute"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"3.+\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(django_http_requests_total_by_view_transport_method_total{namespace=\"$namespace\"}[5m])) by(method, view) > 0)",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "99 quantile"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{namespace=\"$namespace\"}[5m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of Requests by Processing Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of Responses by Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_body_total_bytes_bucket{namespace=\"$namespace\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}