apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-glitchtip-project
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana-folder: /grafana-dashboard-definitions/glitchtip
data:
  dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1004889,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "collapsed": false,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 42,
          "panels": [],
          "title": "Overview",
          "type": "row"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${ds}"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 1
          },
          "id": 44,
          "interval": "1m",
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "${ds}"
              },
              "editorMode": "code",
              "expr": "sum by (organization) (max(delta(glitchtip_events[10m])/10) by (organization, project))",
              "hide": false,
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "B"
            }
          ],
          "title": "Organization Events Rate",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${ds}"
          },
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 100
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 6,
            "x": 0,
            "y": 10
          },
          "id": 49,
          "interval": "1m",
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": false
            },
            "timezone": [
              "utc"
            ],
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "repeat": "project",
          "repeatDirection": "h",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "P21873DB8DE1CE799"
              },
              "editorMode": "code",
              "expr": "max(delta(glitchtip_events{organization=~\"$org\", project=\"$project\"}[10m])/ 10)",
              "instant": false,
              "legendFormat": "Events/Minute",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "$project: Events Rate",
          "transparent": true,
          "type": "timeseries"
        }
      ],
      "refresh": "",
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "glitchtip",
              "value": "glitchtip"
            },
            "hide": 0,
            "includeAll": false,
            "label": "Glitchtip Instance",
            "multi": false,
            "name": "instance",
            "options": [
              {
                "selected": true,
                "text": "glitchtip",
                "value": "glitchtip"
              },
              {
                "selected": false,
                "text": "error-tracking",
                "value": "error-tracking"
              }
            ],
            "query": "glitchtip, error-tracking",
            "queryValue": "",
            "skipUrlSync": false,
            "type": "custom"
          },
          {
            "current": {
              "selected": false,
              "text": "prod",
              "value": "app-sre-prod-04-prometheus"
            },
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "env",
            "options": [
              {
                "selected": true,
                "text": "prod",
                "value": "app-sre-prod-04-prometheus"
              },
              {
                "selected": false,
                "text": "stage",
                "value": "app-sre-stage-01-prometheus"
              }
            ],
            "query": "prod : app-sre-prod-04-prometheus, stage : app-sre-stage-01-prometheus",
            "queryValue": "",
            "skipUrlSync": false,
            "type": "custom"
          },
          {
            "current": {
              "selected": false,
              "text": "app-sre-prod-04-prometheus",
              "value": "P3CBCA2291C540C18"
            },
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "ds",
            "options": [],
            "query": "prometheus",
            "refresh": 1,
            "regex": "/$env/",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "current": {
              "selected": false,
              "text": "glitchtip-production",
              "value": "glitchtip-production"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "${ds}"
            },
            "definition": "label_values(django_http_requests_total_by_method_total, namespace)",
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "namespace",
            "options": [],
            "query": {
              "query": "label_values(django_http_requests_total_by_method_total, namespace)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 1,
            "regex": "/${instance}-${env:text}.*/",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "ocm"
              ],
              "value": [
                "ocm"
              ]
            },
            "datasource": {
              "type": "prometheus",
              "uid": "${ds}"
            },
            "definition": "label_values(glitchtip_events,organization)",
            "hide": 0,
            "includeAll": false,
            "multi": true,
            "name": "org",
            "options": [],
            "query": {
              "qryType": 1,
              "query": "label_values(glitchtip_events,organization)",
              "refId": "PrometheusVariableQueryEditor-VariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": {
              "type": "prometheus",
              "uid": "${ds}"
            },
            "definition": "label_values(glitchtip_events{organization=~\"$org\"},project)",
            "hide": 0,
            "includeAll": true,
            "multi": true,
            "name": "project",
            "options": [],
            "query": {
              "qryType": 1,
              "query": "label_values(glitchtip_events{organization=~\"$org\"},project)",
              "refId": "PrometheusVariableQueryEditor-VariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-12h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Glitchtip Projects",
      "uid": "dejux9gubx2wwc",
      "version": 2,
      "weekStart": ""
    }
