{
 "title": "Glitchtip Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Glitchtip Instance", "query": "glitchtip" },
   {
    "name": "env",
    "query": "prod : app-sre-prod-04-prometheus, stage : app-sre-stage-01-prometheus"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(django_http_requests_total_by_method_total, namespace)"
    }
   },
   {
    "name": "aws_env",
    "query": "prod : aws-resources-exporter-production, stage : aws-resources-exporter-stage"
   },
   { "name": "aws_ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_backend_http_responses_total{code=\"5xx\", exported_namespace=\"$namespace\"}[$__range]))\n/\nsum(increase(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace)(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\", code=\"5xx\"}[$__interval])) /\nsum by (exported_namespace)(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Events/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_view_transport_method_total{namespace=\"$namespace\", view=~\".*event_envelope.*|api:event_store.*\"}[$__interval]) * 60)",
     "legendFormat": "Events/Minute"
    }
   ]
  },
  {
   "title": "Number of Organizations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(glitchtip_organizations{namespace=\"$namespace\"})",
     "legendFormat": "Number of Orgs"
    }
   ]
  },
  {
   "title": "Number of Projects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(glitchtip_projects{namespace=\"$namespace\"}) by (organization))",
     "legendFormat": "Number of Prjs"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "RDS Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_rds_database_connections_average{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "RDS Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(dbinstance_identifier) (aws_rds_free_storage_space_sum{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by(dbinstance_identifier) (aws_resources_exporter_rds_allocatedstorage{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(aws_rds_read_iops_average{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "ReadIOPS"
    },
    {
     "expr": "sum(aws_rds_write_iops_average{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "WriteIOPS"
    }
   ]
  },
  {
   "title": "ReadLatency/WriteLatency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds" },
     "expr": "sum(aws_rds_read_latency_average{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "ReadLatency",
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$rds" },
     "expr": "sum(aws_rds_write_latency_average{dbinstance_identifier=~\"${instance}-${env:text}.*\"})",
     "legendFormat": "WriteLatency",
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ElasticCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory Usage: Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(aws_elasticache_database_memory_usage_percentage_average{cache_cluster_id=~\"${instance}-.*${env:text}.*\"})",
     "legendFormat": "Mem%",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Usage: Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(aws_elasticache_engine_cpuutilization_average{cache_cluster_id=~\"${instance}-.*${env:text}.*\"})",
     "legendFormat": "CPU%",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(aws_elasticache_curr_items_average{cache_cluster_id=~\"${instance}-.*${env:text}.*\"})",
     "legendFormat": "Items",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Pod Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Web Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"web\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Web Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\"glitchtip-web.+\"}",
     "legendFormat": "{{pod}} CPU Usage"
    },
    {
     "expr": "avg(kube_pod_resource_limit{namespace=\"$namespace\", pod=~\"glitchtip-web.+\", resource=\"cpu\"})",
     "legendFormat": "CPU  Limit"
    },
    {
     "expr": "avg(kube_pod_resource_limit{namespace=\"$namespace\", pod=~\"glitchtip-web.+\", resource=\"cpu\"})",
     "legendFormat": "CPU Request"
    }
   ]
  },
  {
   "title": "Worker Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"worker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\"glitchtip-worker.+\"}",
     "legendFormat": "{{pod}} CPU Usage"
    },
    {
     "expr": "avg(kube_pod_resource_limit{namespace=\"$namespace\", pod=~\"glitchtip-worker.+\", resource=\"cpu\"})",
     "legendFormat": "CPU  Limit"
    },
    {
     "expr": "avg(kube_pod_resource_limit{namespace=\"$namespace\", pod=~\"glitchtip-worker.+\", resource=\"cpu\"})",
     "legendFormat": "CPU Request"
    }
   ]
  },
  { "title": "Path latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Event Upload Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"$namespace\",method=\"POST\",view=~\".*event.*\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"$namespace\",method=\"POST\",view=~\".*event_envelope.*|api:event_store.*\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=\"$namespace\",method=\"POST\",view=~\".*event_envelope.*|api:event_store.*\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}